### ISSUE TITLE
Error: Invariant failed: SESSION_SECRET must be set for authentication to work

### ISSUE THREAD

**Issue by f1eeman** [feature-sliced/tutorial-conduit#1]
### What version of Remix are you using?
2.9.2

### Steps to Reproduce
npm i
npm run generate-api-types
see error

### Expected Behavior
run dev should load the initial page

### Actual Behavior
getting this error:

$ npm run dev

```
> dev
> remix dev --manual


 💿  remix dev

 info  building...
 info  built (1.7s)
Error: Invariant failed: SESSION_SECRET must be set for authentication to work
    at invariant (file:///C:/projects/templates/conduit-draft/node_modules/tiny-invariant/dist/esm/tiny-invariant.js:12:11)
    at file:///C:/projects/templates/conduit-draft/shared/api/auth.server.ts:6:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at run (C:\projects\templates\conduit-draft\node_modules\@remix-run\serve\dist\cli.js:112:15)
```

**Comment by f1eeman** [comment]
Solved a problem. 
I just need to rename the .env.example file to .env.

**Comment by electfreak** [comment]
@illright renaming `.env.example` works but isn't it worth mention in README or smth?

**Comment by illright** [comment]
Yeah, it might be nice to mention in the README how to start this project
